### ISSUE TITLE
The installation instructions could be more clearer

### ISSUE THREAD

**Issue by NiiYemo** [aws-solutions-library-samples/guidance-for-aws-deepracer-event-management#64]
Hello I find the installation instructions difficult to follow. Is the entire installation process to be run on the aws console? Or are they meant to be run on your local system or some in the console and some in the aws cloud.

Any clarity would be welcome please

**Comment by larsll** [comment]
Assuming you start here: https://github.com/aws-solutions-library-samples/guidance-for-aws-deepracer-event-management/blob/main/README.md#option-1-deploy-drem-for-use-at-an-event -- then those steps can be run on any computer (laptop, EC2, etc.) as long as you have the right credentials available.

The installation process is so that a at `make install` CodePipeline is created in the region of choice, which then pulls the source code from GIT and builds and deploys everything.

**Comment by StevenAskwith** [comment]
The installation is ran from your command line, where-ever that happens to be, e.g. EC2, local mac, local windows machine, etc. This is in the instructions: 
[In your terminal of command line, enter the following commands:...](https://github.com/aws-solutions-library-samples/guidance-for-aws-deepracer-event-management?tab=readme-ov-file#step-1-setup-environment)

This deploys the pipeline which will then create the DREM website for you via CodePipeline/CodeBuild.
